### ISSUE TITLE
Search Posts, attachment limits and attaching Terms

### ISSUE THREAD

**Issue by lmartins** [WebDevStudios/cmb2-attached-posts#7]
While really useful as it is, I believe it could really improve with a few changes:
1. Search posts
   I've noticed theres a field dedicated to that functionality, but something in the lines of what ACF does would be really awesome. When you have a lot of posts, the current presentation won't scale well, hence the need for some sort of search functionality.
2. Limit Attachments
   Would be possible to limit ao many attachments the user can add?
3. Attaching Terms
   It would be very useful if we could attach other types of contents, such as categories, custom post-types, etc.

Thank you CMB2 and this useful extension.

**Comment by jtsternberg** [comment]
1. My goal is to eventually combine this library with [the 
CMB2 Post Search field type](https://github.com/WebDevStudios/CMB2-Post-Search-field).
2. Interesting idea. It'll likely sit on the back-burner till we need it for a certain project, but if you care to submit a PR, we'd be happy to look at it.
3. You can definitely modify the query args if you [follow the example](https://github.com/WebDevStudios/cmb2-attached-posts/blob/master/example-field-setup.php#L42-L44) and have it use any post-type you want. That being said, other types of data would be a cool option.

**Comment by monecchi** [comment]
What about getting special custom post types such as WooCommerce's `product_variation`? I'm using the the [CMB2 Post Search field type](https://github.com/WebDevStudios/CMB2-Post-Search-field), but it does not return that WooCommerce specific custom post type by default, and even by changing its `$args`, I'd only get one id at a time.

On my usage scenario, I'm editing a custom post type under WP Admin for which I've set a few custom fields, one of these fields is a select field that lives within a repeatable group, so for each repeatable group I'd need to render a select field with WooCommerce product variations as an array of options.

In order to do that I'm using a function to query posts of type `product_variation`, and then return the options for the select field, but the issue is that I need to limit the product variations display to the post which is been edited, however, the function I'm using returns all the store's available product variations.

Here's the function:

        function cmb2_get_term_options( $query_args ) {
                   
		   $id = get_post_meta( get_the_ID(), '_prefix_related_product', true ); // trying to grab the ID set to the post with the CMB2 Post Search field type plugin

		     $args = wp_parse_args( $query_args, array(
				'post_type'   => 'product_variation',
				'post_status' => array( 'private', 'publish' ),
				'numberposts' => -1,
				'orderby'     => 'menu_order',
				'order'       => 'asc',
				'post_parent' => $id
		     ) );

		    $post_options = array();

		     // return post type as options
		     $posts = get_posts( $args );

		     $post_options = array();
		     if ( $posts ) {
		         foreach ( $posts as $post ) {
		           $post_options[ $post->ID ] = $post->post_title;
		         }
		     }

		     return $post_options;
        }

An here's the CMB2 field

        $cmb_group->add_group_field( $group_field_id, array(
		'name' => __( 'Test Taxonomy Select', 'mytheme' ),
		'desc' => 'Description Goes Here',
		'id' => 'variations_taxonomy_select',
		'taxonomy' => 'product_variation', //Enter Taxonomy Slug
		'type' => 'select',
        'options' => cmb2_get_term_options( array( 'post_type' => 'product_variation' ) )  
        ) );   


Does anyone know of an add-on or CMB2 plugin which might help me to achieve that?

Thanks in advance.

**Comment by chriscoyier** [comment]
Yeah! Combining this with "Post Search Field Type" would be reallllllly useful. 

I just got this installed, in which to attempt to create kind of curated/arranged "guides" of existing posts/pages/etc, but it's not really possible because I can't find the content in which to add. And it doesn't look like I can switch to "Post Search" field type, because then I lose the ability to re-arrange.

**Comment by jtsternberg** [comment]
Let's see if I can whip something up

**Comment by jtsternberg** [comment]
Ok, the deed is done. Let me know how it works for you guys.

If you're familiar with the `pre_get_posts` hook, and the `$query` object, you can modify the search modal's results by specifying a callback on the `'attached_posts_search_query_cb'` field parameter. (similar to [other `*_cb` parameters](https://github.com/WebDevStudios/CMB2/wiki/Field-Parameters#show_on_cb)). The callback gets the `$query` object passed to it.

**Comment by chriscoyier** [comment]
this is sweet - best of both worlds. Now we can set up queries to prefill the list with relevant stuff on load AND use search.

**Comment by monecchi** [comment]
Awesome!
